### ISSUE TITLE
Disbursements and expenditures

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#13]
## Description

Individual actual financial disbursements and expenditures must be related to individual activities and must be on a per-transaction basis.

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Proposed test

```python
   Given an IATI activity 
   And the activity is current 
   And `activity-status/@code` is one of 2, 3 or 4 
   Then `transaction[transaction-type/@code="3" or transaction-type/@code="D" or transaction-type/@code="4" or transaction-type/@code="E"]` should be present and of non-zero value
```

**Comment by malclopez** [comment]
The tester is expecting that all activities under implementation should have disbursements. It is possible that some of the projects being implemented have zero disbursement due to various reasons (e.g., the project may still be in its early stage of implementation or may be encountering some delays).

**Comment by cmmarschner** [comment]
I agree with the comment above. MCC's activities have up to five years to complete once they begin (many are large construction works). We do not EXPECT to have disbursements on all of them right away. Prefer a test that compares other sources of data to what an organization publishes in IATI. The test structure should focus on whether organizations are publishing a comprehensive disbursement data set, not whether an activity has disbursed or not since you have no way of knowing whether a disbursement was expected. Alternatively, allow "0" values since that is often a valid answer on whether a disbursement was made during a period.

**Comment by publishwhatyoufund** [comment]
Since some activities may be in implementation without a disbursement or expenditure we will modify this test to allow a "0" value. The logical way to do this will be to use a regular expenditure reported amount of "0" rather than adding a zero value disbursement.
