### ISSUE TITLE
Evaluations

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/latest-index-indicator-definitions#33]
## Description

Evaluation documents consider what the activity achieved, whether the intended objectives were met, what the major factors influencing the achievement or non-achievement of the objectives were and an assessment of the impact, effect and value of the activity.

This is only expected if the activity is in the completion or post-completion phase. 

This is not expected if the default aid type code is administrative costs (G01).

## Proposed test
```python
   For each current activity,
   i​f `activity-status/@code` i​s one of (3, 4)
   a​nd `default-aid-type/@code` i​s n​ot G01
   o​r `document-link/category[@code="A07"]` is present
   then `document-link/category[@code="A07"]` should be present
```

**Comment by rjboles** [comment]
Depending on the nature of the activity, some USAID activities will never have an evaluation to publish. We recommend that these cases should be excluded from the test sample, otherwise donors are penalized not on the basis of transparency but rather on a notion that nearly all (excluding aid type G01) activities should have an evaluation. We propose excluding additional aid types from the sample such as AO1 General budget support, B02 Core contributions to multilateral institutions, B04 Basket funds/pooled funding. While this would not exclude all activities that will never have an evaluation, we believe these changes will better target the test’s measurement of transparency.

**Comment by jzheng-79** [comment]
Our evaluation typically covers country programme, thematic, multi-country, joint UN, etc., but not for individual output (IATI activity). 
We would like this to be noted and properly assessed based during the assessment process

**Comment by publishwhatyoufund** [comment]
@rjboles 
Thank you for your input here. It would be too difficult to exclude specific activities from the evaluations test since there is unlikely to be a common approach across donors in the Index.  This goes for aid types A01 and B02 for which some organisations may choose to produce evaluations or publish evaluations that have been produced by recipients.

@jzheng-79 
Thank you for your input. For this indicator we would pass any evaluation published against an activity that includes an evaluation of that specific activity, even if this is part of a wider programme, sector or geographic evaluation.
